# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         parselog
version:      0.04
version_from: 
installdirs:  site
requires:
    DateTime:                      0
    LockFile::Simple:              0
    RRDs:                          0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
